import type { AlgorithmInfo } from '../types';

export const algorithms: AlgorithmInfo[] = [
  {
    id: 'bubble',
    name: 'Bubble Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: true,
    description: 'Repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order.',
  },
  {
    id: 'selection',
    name: 'Selection Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: false,
    description: 'Divides the input into a sorted and unsorted region, repeatedly selecting the smallest element from the unsorted region.',
  },
  {
    id: 'insertion',
    name: 'Insertion Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: true,
    description: 'Builds the final sorted array one element at a time by repeatedly inserting an element into the sorted portion.',
  },
  {
    id: 'shell',
    name: 'Shell Sort',
    category: 'comparison',
    timeComplexity: 'O(n log² n)',
    stable: false,
    description: 'Generalization of insertion sort that allows exchange of far-apart elements using gap sequences.',
  },
  {
    id: 'quick',
    name: 'Quick Sort',
    category: 'comparison',
    timeComplexity: 'O(n log n)',
    stable: false,
    description: 'Picks a pivot element and partitions the array around it, then recursively sorts the partitions.',
  },
  {
    id: 'merge',
    name: 'Merge Sort',
    category: 'comparison',
    timeComplexity: 'O(n log n)',
    stable: true,
    description: 'Divides the array into halves, recursively sorts them, then merges the sorted halves.',
  },
  {
    id: 'heap',
    name: 'Heap Sort',
    category: 'comparison',
    timeComplexity: 'O(n log n)',
    stable: false,
    description: 'Builds a max-heap from the array, then repeatedly extracts the maximum element.',
  },
  {
    id: 'tim',
    name: 'Tim Sort',
    category: 'comparison',
    timeComplexity: 'O(n log n)',
    stable: true,
    description: 'Hybrid sorting algorithm derived from merge sort and insertion sort, designed for real-world data.',
  },
  {
    id: 'cocktail',
    name: 'Cocktail Shaker Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: true,
    description: 'Bidirectional bubble sort that passes through the list in both directions alternately.',
  },
  {
    id: 'comb',
    name: 'Comb Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: false,
    description: 'Improves on bubble sort by using a gap sequence that shrinks by a factor of 1.3.',
  },
  {
    id: 'gnome',
    name: 'Gnome Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: true,
    description: 'Similar to insertion sort but moves elements by swapping a gnome-like cursor forward and backward.',
  },
  {
    id: 'counting',
    name: 'Counting Sort',
    category: 'linear',
    timeComplexity: 'O(n + k)',
    stable: true,
    description: 'Non-comparison sort that counts occurrences of each integer value and uses that to place elements.',
  },
  {
    id: 'radix',
    name: 'Radix Sort',
    category: 'linear',
    timeComplexity: 'O(nk)',
    stable: true,
    description: 'Non-comparison sort that processes digits individually, sorting by the least significant digit first.',
  },
  {
    id: 'bucket',
    name: 'Bucket Sort',
    category: 'linear',
    timeComplexity: 'O(n + k)',
    stable: true,
    description: 'Distributes elements into buckets and sorts each bucket individually using insertion sort.',
  },
  {
    id: 'bogo',
    name: 'Bogo Sort',
    category: 'comparison',
    timeComplexity: 'O((n+1)!)',
    stable: false,
    description: 'Randomly shuffles the array until it is sorted. Capped at 1000 attempts for practicality.',
  },
];
