import type { AlgorithmInfo } from '../types';

export const algorithms: AlgorithmInfo[] = [
  {
    id: 'bubble',
    name: 'Bubble Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: true,
    description: 'The classic. Adjacent swaps until sorted. Slow but you learn it once.',
  },
  {
    id: 'selection',
    name: 'Selection Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: false,
    description: 'Finds the smallest element and puts it at the front. Repeatedly. Does not care about existing order.',
  },
  {
    id: 'insertion',
    name: 'Insertion Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: true,
    description: 'Good for small or nearly-sorted arrays. Picks one element, inserts it where it belongs.',
  },
  {
    id: 'shell',
    name: 'Shell Sort',
    category: 'comparison',
    timeComplexity: 'O(n log² n)',
    stable: false,
    description: 'Insertion sort but smarter — swaps far-apart elements first using a decreasing gap.',
  },
  {
    id: 'quick',
    name: 'Quick Sort',
    category: 'comparison',
    timeComplexity: 'O(n log n)',
    stable: false,
    description: 'Pick a pivot, partition around it, recurse. Fast in practice, terrible for already-sorted data with bad pivot choice.',
  },
  {
    id: 'merge',
    name: 'Merge Sort',
    category: 'comparison',
    timeComplexity: 'O(n log n)',
    stable: true,
    description: 'Divide and conquer. Splits the array in half until single elements, then merges back up in sorted order.',
  },
  {
    id: 'heap',
    name: 'Heap Sort',
    category: 'comparison',
    timeComplexity: 'O(n log n)',
    stable: false,
    description: 'Builds a max-heap, then repeatedly pulls the largest element off the top.',
  },
  {
    id: 'tim',
    name: 'Tim Sort',
    category: 'comparison',
    timeComplexity: 'O(n log n)',
    stable: true,
    description: 'Python and JS use this. Merge sort + insertion sort hybrid optimized for real-world partially-sorted data.',
  },
  {
    id: 'cocktail',
    name: 'Cocktail Shaker Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: true,
    description: 'Bubble sort but bidirectional. Goes left-to-right then right-to-left each pass.',
  },
  {
    id: 'comb',
    name: 'Comb Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: false,
    description: 'Bubble sort with a shrinking gap. The 1.3 shrink factor is empirically the best.',
  },
  {
    id: 'gnome',
    name: 'Gnome Sort',
    category: 'comparison',
    timeComplexity: 'O(n²)',
    stable: true,
    description: 'Like insertion sort but swaps backward instead of shifting. Also called stupid sort.',
  },
  {
    id: 'counting',
    name: 'Counting Sort',
    category: 'linear',
    timeComplexity: 'O(n + k)',
    stable: true,
    description: 'Counts how many times each value appears, then reconstructs. Only works for integers with limited range.',
  },
  {
    id: 'radix',
    name: 'Radix Sort',
    category: 'linear',
    timeComplexity: 'O(nk)',
    stable: true,
    description: 'Sorts digit-by-digit from least significant to most. Uses counting sort as a subroutine.',
  },
  {
    id: 'bucket',
    name: 'Bucket Sort',
    category: 'linear',
    timeComplexity: 'O(n + k)',
    stable: true,
    description: 'Distributes elements into buckets, sorts each bucket (usually with insertion sort), concatenates.',
  },
  {
    id: 'bogo',
    name: 'Bogo Sort',
    category: 'comparison',
    timeComplexity: 'O((n+1)!)',
    stable: false,
    description: 'Randomly shuffles until sorted. Included because it is funny. Falls back to native sort after 1000 attempts.',
  },
];
